meta_product_name: "MealMate"
meta_title: "MealMate connects volunteers with community members in need"
meta_description: "Through MealMate, members in risk groups can order produce and community volunteers deliver it to their door"
meta_image: "cover.png" # should exist in `app/assets/images/`
twitter_account: "@suburbanfarm1"   # required for Twitter Cards
